docs(developers): add zkSBT SDK
Manta-Network/docs pull request #148
Opened 2023-03-28 15:57 UTC by jincan39

2023-03-29 08:58 UTC, ghzlatarev commented on docs/calamari/DevelopOnCalamari.md
> +You can request each of the four supported tokens (`DOL`, `KAR`, `KSM`, `MOVR`) once per UTC day. If you request the same token twice in the same day, the faucet bot will only respond with the status
can they check Calamari addresses here ?

2023-03-29 13:49 UTC, jincan39 commented on docs/calamari/DevelopOnCalamari.md
> +Dolphin testnet chain id is `2084`
@ghzlatarev Do you know what's the chain id of Calamari testnet?

2023-03-29 13:52 UTC, jincan39 commented on docs/calamari/DevelopOnCalamari.md
> +* `Manta zkSBT SDK`: zkSBT sdk is extension of manta-pay sdk, and add some custom logic, including:
Yeah think it need to be discussed

2023-03-30 02:54 UTC, jincan39 commented on docs/calamari/DevelopOnCalamari.md
> +* `Manta zkSBT SDK`: zkSBT sdk is extension of manta-pay sdk, and add some custom logic, including:
it's the superset of manta.js, so i think they are parallel.

2023-03-30 19:13 UTC, Garandor commented
![image](https://user-images.githubusercontent.com/4237655/228940031-06519e3a-b742-46b3-b18c-12751019f42d.png)
this sidebar structure looks needlessly repetititve.
Maybe change the file name to "Get Started" or smth like that

2023-03-31 15:49 UTC, Garandor commented on docs/calamari/DevelopOnDolphin.md
> +`calamari-localdev` exposes the websocket at port 9944 by default, if you need to customize this, you can pass an additional parameter `--ws-port 42069` to use e.g port 42069 instead.
`dolphin-localdev` everywhere

2023-03-31 15:49 UTC, Garandor commented on docs/calamari/DevelopOnDolphin.md
> +- connecting to a node on the live Calamari Network.
calamari network. replace everywhere...

2023-04-03 13:41 UTC, Garandor requested changes
There are still some mentions of Calamari in the dolphin guide

2023-04-03 23:16 UTC, Garandor approved these changes

2023-04-04 02:59 UTC, merged