Staking Docs
Manta-Network/docs pull request #84
Opened 2022-09-14 08:38 UTC by Garandor

Signed-off-by: Adam Reif <Garandor@manta.network>

2022-09-21 06:11 UTC, grenade requested changes
please remove the term `whitelist` from this pr.

2022-10-04 16:29 UTC, MantaMikeSalwet commented on docs/calamari/Staking/01-Overview.md
> +Staking is active on Calamari Network starting v3.4.0
add: "...starting with v3.4.0"

2022-10-04 16:31 UTC, MantaMikeSalwet commented on docs/calamari/Staking/01-Overview.md
> +Similar to other Layer 1 blockchains, block producers are selected out of a set of candidates based on a total KMA stake backing each specific block producer candidate - in our case called a `collato
Change "based on a total" to "based on the total"

2022-10-04 16:32 UTC, MantaMikeSalwet commented on docs/calamari/Staking/01-Overview.md
> +On Kusama, an on-chain election occurs to distribute tokens among backed nodes, on Calamari a delegator always picks one concrete collator and a concrete number of KMA they wish to delegate to that c
change "distribute tokens" to "distribute KSM tokens" to clarify Kusama vs Calamari protocol rules.

2022-10-04 20:57 UTC, stechu approved these changes

2022-10-04 21:01 UTC, grenade approved these changes

2022-10-05 04:11 UTC, merged